title: Bioinformatics with Barry!
logo: https://bioboot.github.io/bggn213_S19/assets/img/logo.png
description: I had no idea what I was doing before taking this class.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
